### ISSUE TITLE
Unable to require jingle

### ISSUE THREAD

**Issue by CharlesWall** [otalk/jingle.js#27]
From the command line the following has ceased to work. 
npm install jingle
node -i
require('jingle')

It fails with the following error

ReferenceError: navigator is not defined
    at Object.<anonymous> (/Users/charleswall/temp/node_modules/jingle/node_modules/jingle-media-session/node_modules/rtcpeerconnection/node_modules/webrtc-adapter-test/adapter.js:39:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/charleswall/temp/node_modules/jingle/node_modules/jingle-media-session/node_modules/rtcpeerconnection/rtcpeerconnection.js:8:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

I've done some digging and several dependencies in there was a change that I think caused the issue.
https://github.com/otalk/RTCPeerConnection/commit/2716b3a527685ed0fe8dc6bea07068e476f9e516#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

I thought I'd post it here in case you have a work around. It is currently a blocker for us. I will continue to research the issue, but any help is appreciated.

**Comment by legastero** [comment]
Oh, thanks for the report!

You can add a requirement to your app for `rtcpeerconnection` at `v3.0.14` to use the version from before that issue until this is fixed.

**Comment by legastero** [comment]
I've updated `jingle-media-session` to use `rtcpeerconnection@3.0.x` for now until the underlying issue here is resolved. So things should work for you again now if you re-install your dependencies.

**Comment by xdumaine** [comment]
I'm working on a PR for adapter.js to not blow up when required in a node context.

**Comment by xdumaine** [comment]
This should resolve this issue https://github.com/webrtc/adapter/pull/67

**Comment by xdumaine** [comment]
I'd guess that the project *probably doesn't need* to require jingle in a node context, but if it is (for build and/or test purposes), having adapter.js not fail would be good.

**Comment by fippo** [comment]
this was fixed in adapter.js, right?

**Comment by xdumaine** [comment]
Yes, this should be able to be closed.
